oauth_consumer_key = 'System-wide: golang (https://github.com/fourdollars/lp-api)'
oauth_token = 'sQnvgvQ1wKH9Fbqt3wdb'
oauth_token_secret = '3S0f9tF6NX1BmV5Bf1FH88MSlQkT8jfdKn8VTJ1tggHTw6TbcNr6jsvp4jgxx1pBSdccwMDW9NRtwPf2'
